# h2
spring:
  datasource:
    url: jdbc:h2:mem:kpsecdb;MODE=MySQL
    platform: h2
    username: kpsec
    password: kpsec
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
